In [9]:
import pandas as pd

df = pd.read_csv('SalesData.csv')
print(df)

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda              NaN

In [10]:
df.tail(2) ## from the end how many records you wanna see

               Region                Country Item Type
3  Sub-Saharan Africa  Sao Tome and Principe    Fruits
4  Sub-Saharan Africa                 Rwanda       NaN

In [11]:
df.describe()

                    Region Country  Item Type
count                    5       5          4
unique                   4       5          4
top     Sub-Saharan Africa  Tuvalu  Baby Food
freq                     2       1          1

In [13]:
##Handling missing values
df.isnull()

   Region  Country  Item Type
0   False    False      False
1   False    False      False
2   False    False      False
3   False    False      False
4   False    False       True

In [17]:
df.isnull().any()
# df.isnull().any(axis=1)

Region       False
Country      False
Item Type     True
dtype: bool

In [19]:
df.isnull().sum()

Region       0
Country      0
Item Type    1
dtype: int64

In [21]:
df.fillna(0)  ## missing value in the records will fill the value 0

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda                0

In [23]:
 df.dtypes

Region       object
Country      object
Item Type    object
dtype: object

In [26]:
##renaming the columns
df = df.rename(columns={'Region' : "New Region"})
df

                          New Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda              NaN