In [169]:
import pandas as pd

In [170]:
# Series
data =[1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [171]:
## Ceate a series from dictionary

data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [172]:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
print(pd.Series(data, index= index))

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [173]:
## Dataframe

## Create a dataframe from a dictionary of list
data = {
    'Name' : ['Sai', 'John', 'Jack'],
    'Age' : [25, 30, 35],
    'City' : ['Bangalore', 'New York', 'Florida']
}

df = pd.DataFrame(data)
print(df)

   Name  Age       City
0   Sai   25  Bangalore
1  John   30   New York
2  Jack   35    Florida

In [174]:
import numpy as np
print(np.array(data))

{'Name': ['Sai', 'John', 'Jack'], 'Age': [25, 30, 35], 'City': ['Bangalore', 'New York', 'Florida']}

In [175]:
## Create a Data frame from a list of dictionary

data = [
{'Name' : 'Krish', 'Age' : 25, 'City': 'Bangalore'},
{'Name' : 'Jhon', 'Age' : 24, 'City': 'New York'},
{'Name' : 'Jack', 'Age' : 28, 'City': 'USA'}
]

df = pd.DataFrame(data)
print(df)

    Name  Age       City
0  Krish   25  Bangalore
1   Jhon   24   New York
2   Jack   28        USA

In [176]:
df = pd.read_csv('SalesData.csv')
print(df.head(5)) ## head : first 5records
# print(df.tail(5))

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda  Office Supplies

In [177]:
df['Region'].head(5)  ## specific column

0                Australia and Oceania
1    Central America and the Caribbean
2                               Europe
3                   Sub-Saharan Africa
4                   Sub-Saharan Africa
Name: Region, dtype: object

In [178]:
df.loc[0]  ## Row index

Region       Australia and Oceania
Country                     Tuvalu
Item Type                Baby Food
Name: 0, dtype: object

In [179]:
df.iloc[0] ## 
df.iloc[0][1]

C:\Users\z004w9yf\AppData\Local\Temp\ipykernel_232\4156783192.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

'Tuvalu'

In [180]:
df.at[1, 'Region']

'Central America and the Caribbean'

In [181]:
##Data manupulation with data frame
df

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda  Office Supplies

In [182]:
df['Salary'] = [100000, 200000, 300000, 400000, 500000]
df

,Region,Country,Item Type,Salary
0,Australia and Oceania,Tuvalu,Baby Food,100000
1,Central America and the Caribbean,Grenada,Cereal,200000
2,Europe,Russia,Office Supplies,300000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,400000
4,Sub-Saharan Africa,Rwanda,Office Supplies,500000

In [183]:
df.drop('Salary', axis=1, inplace=True) ## inplace make it perminante drop of column

In [184]:
df

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda  Office Supplies

In [185]:
df.drop(0) ## Not perminant
df

                              Region                Country        Item Type
0              Australia and Oceania                 Tuvalu        Baby Food
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda  Office Supplies

In [ ]:
df.drop(0, inplace=True) ## Removed record perminantly

In [188]:
df

                              Region                Country        Item Type
1  Central America and the Caribbean                Grenada           Cereal
2                             Europe                 Russia  Office Supplies
3                 Sub-Saharan Africa  Sao Tome and Principe           Fruits
4                 Sub-Saharan Africa                 Rwanda  Office Supplies

In [189]:
df.describe()

                    Region  Country        Item Type
count                    4        4                4
unique                   3        4                3
top     Sub-Saharan Africa  Grenada  Office Supplies
freq                     2        1                2